
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync

    - name: Package Application
      run: |
        .\.venv\Scripts\pyinstaller.exe .\minesweeper.spec

    - uses: actions/upload-artifact@v4
      with:
        name: minesweeper.exe
        path: dist/minesweeper.exe